name: fruti_hub_dashboard
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  dartz: ^0.10.1
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  skeletonizer: ^2.1.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils
  filename: app_images.dart
